version: "3.8"
services:
  app:
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      DB_HOST: db
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    command: yarn dev
    depends_on:
      - db

  db:
    image: postgres:12.7-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    # volumes:
    # - db-postgres:/var/lib/postgresql/data
